### ISSUE TITLE
support chunked encoding/streaming

### ISSUE THREAD

**Issue by mo-gr** [vulcand/vulcand#215]
Unless I get something very wrong, vulcans (or oxy?) currently doesn't support streaming proxied responses. Oxy even seems to explicitly buffer chunked responses and flush them in one go to the original client.

What is the rationale behind that? Is there a specific reason, why you chose not to support chunked responses?

What would be the best way to support chunking in vulcand? It seems, like a custom middleware won't work here.

**Comment by timchen** [comment]
+1

**Comment by JonGretar** [comment]
:+1:

**Comment by klizhentas** [comment]
I originally impelemented it this way because it reduces load and risk for backend services - with vulcand they are guaranteed to get the same request with well defined length and makes it more predictable as backend services will be talking on local network, not through the internet.

However I understand that some use-cases may need the opposite behaviour, so PR's are welcome :) This should be a parameter for a fronted turning this feature off in Vulcand and Oxy.

**Comment by archisgore** [comment]
I made the relevant change in Oxy here: https://github.com/vulcand/oxy/pull/45

The vulcan change is here: https://github.com/vulcand/vulcand/pull/292

I posted a sample go app, which should allow you to create a local chunking endpoint to test against.
