### ISSUE TITLE
Native Support for Let's Encrypt

### ISSUE THREAD

**Issue by pquerna** [vulcand/vulcand#270]
Vulcan should be able to be configured to automatically register hostnames from [Let's Encrypt](https://letsencrypt.org/).  Ideally the internal interfaces could be used for other automated CA's if/when they are available.

The Simple HTTP validation method has just has a few paths under '.well-known/acme-challenge' that vulcand would need to handle internally:

https://letsencrypt.github.io/acme-spec/#rfc.section.7.1

The backing store the needed data for this probably be in etcd so that if vulcand is operating in a cluster, any instance can respond

**Comment by tboerger** [comment]
:+1: Should be an awesome feature

**Comment by derDieDasJojo** [comment]
:thumbsup: would be awesome

**Comment by tboerger** [comment]
Maybe we can use https://github.com/google/goacme to integrate it? The caddy webserver already supports it natively.

**Comment by errm** [comment]
:+1: sounds like a great feature, especially for deploying short lived services for QA and the like.

**Comment by guilhem** [comment]
This feature + HTTP2 #188 would be awesome

**Comment by horkhe** [comment]
@powellchristoph or @russjones is any of you wanna take care of this? Asking since both of you has looked into that stuff.

**Comment by archisgore** [comment]
I'm going to take this up. One because I want it personally for our website polyverse.io, and another because moving private keys is so stupid and unnecessary! :-)

Anyway, can we get some spec discussion going early, so that by the time I'm done, we won't have to go through a large review cycle to narrow it down?

Can one of  you tell me what you had in mind for how you would want to specify Let's Encrypt to be used to generate a cert? How would the flow work? What would the json blobs in etcd look like in your mind?

**Comment by horkhe** [comment]
@archisgore to tell the truth I do not know the let's encrypt mechanics. But if you want to take care of this then a good way to start would be to outline the high level feature design in some document. And then we can provide feedback.

**Comment by archisgore** [comment]
Okay sounds great. I'll just capture it here now.

The crux of Let's Encrypt is automated-certificate generation. The flow is this:

1. You start a webserver that purports itself to be under hostname "foo.bar".
2. The webserver generates a new private key.
3. It contacts Let's Encrypt to generate a cert for that domain using the ACME protocol.
4. Let's Encrypt sends back a challenge you can host (there are about 4 other methods which I don't intend to implement.)
5. This challenge is them placed somewhere under your webserver's path.
6. Let's Encrypt will ping the hostname "foo.bar" for that challenge.
7. If the webserver truly is backing foo.bar, then the challenge is verified and a cert is provided by Let's Encrypt.

The idea here is "You are who you say you are", and thus exposing SSL over Vulcand would be a LOT easier, avoid misconfigured certs, and not require private keys to be managed. Vulcan can rotate them when they're about to expire.

For internal services where you might be testing lots of microservices, this can be a wonderful alternative to self-signed certs. All services can generate certs from a known CA, and be verified that you own the domain.

There is a great ACME implementation in go to do this.

I'll post back later in the week (I'm travelling for a conference), and propose a JSON schema. I was hoping @pquerna had some schema in mind since he proposed the change. If not I'll submit a candidate, and we can discuss it. Let's make sure we can, in the future, extend it to all the other methods of domain verification.

**Comment by archisgore** [comment]
Golang is building an ACME client. https://github.com/golang/crypto/blob/master/acme/acme.go

**Comment by archisgore** [comment]
In PR: https://github.com/vulcand/vulcand/pull/339

**Comment by archisgore** [comment]
This is done!
