### ISSUE TITLE
vulcand build cause error

### ISSUE THREAD

**Issue by auzty** [vulcand/vulcand#288]
Hello, i need to connect my vulcan to my etcd server that using ssl, so i compiled the latest version v0.8.0-beta.3 , 
my env:
Linux Ubuntu 14.04.3 64bit
Go is latest version (v1.6.2) 

my infrastructure : 
Kubernetes with skydns 

i run : 

```
godep save
godep update -goversion
godep get
godep go build
```

and then i get the vulcand binary

but when i use that binary, one of my docker running php5 that using variable "**BASE_URL**" 
it return the internal url that **hello-world.svc.default.cluster.local** instead **hello-world.com**

my research : 
- i suspect the vulcand because when i use the images from docker pull mailgun/vulcan , it's works but didn't support SSL etcd yet. 
- the another docker that running nodejs works fine, the url return from the vulcand is **nodejs-world.com** instead **nodejs.svc.default.cluster.local**

may i missed something when build the vulcand?

Thanks You

**Comment by horkhe** [comment]
Vulcand has all dependency vendored. So you do not need to fiddle with godep yourself. I see that it has been a year since you asked so this is probably not of interest to you anymore. I am closing this issue but feel free to reopen if you still want some resolution. This time I will respond in time, I promise.
